spring.application.name=migajaApp

# Database Configuration

spring.datasource.url= jdbc:h2:mem:hormiga_gasto
spring.datasource.username=sa
spring.datasource.password=

# H2 activate console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true